version: '2' # composeファイルのバージョン
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    volumes:
      - .:/app
    networks:
      - muscle-sns-network
    depends_on:
      - db
  db:
    container_name: muscle-sns-db
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - muscle-sns-db-vol:/var/lib/mysql
    networks:
      - muscle-sns-network

volumes:
  muscle-sns-db-vol:

networks:
  muscle-sns-network:
    driver: bridge
