version: '3' # composeファイルのバージョン
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - muscle-sns-network
    depends_on:
      - db
  db:
    container_name: muscle-sns-db
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mysqlusername
      MYSQL_PASSWORD: mysqluserpass
      MYSQL_ROOT_PASSWORD: mysqlrootpass
      MYSQL_DATABASE: muscle-sns-db
    volumes:
      - muscle-sns-db-vol:/var/lib/mysql
    networks:
      - muscle-sns-network
  redis:
    container_name: muscle-sns-redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - muscle-sns-network

volumes:
  muscle-sns-db-vol:

networks:
  muscle-sns-network:
    driver: bridge