name: deploy

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT_ID: 783167355948
  AWS_REGION: ap-northeast-1
  AWS_IAM_ROLE: S3FullAccessGitHubActions
  AWS_S3_BUCKET: muscle-sns-build

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go 
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.2'
      
      - name: Build
        run: go build -o muscle-SNS ./cmd/main.go
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/S3FullAccessGitHubActions
          role-session-name: ${{ env.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp muscle-SNS s3://${{ env.AWS_S3_BUCKET }}/muscle-SNS
