name: LightsailCD

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > private_key
          chmod 600 private_key
          ssh -oStrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER_NAME }}@${{ secrets.LIGHTSAIL_HOST }} -i private_key "cd /home/ec2-user/muscle-SNS && git fetch --prune && git checkout main && git pull origin main"
        
